// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BotSetup struct {
	ChannelID string
	MessageID string
	CreatedAt pgtype.Timestamp
}

type Char struct {
	ID     int32
	Name   string
	Class  string
	UserID pgtype.Int4
}

type Debt struct {
	ID          int32
	Amount      int64
	LastUpdated pgtype.Timestamp
	UserID      pgtype.Int4
}

type DebtJournal struct {
	ID          int32
	Amount      int64
	Description string
	Date        pgtype.Date
	UserID      pgtype.Int4
}

type Player struct {
	ID   int32
	Name string
}
