apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          env:
            - name: DATABASE_CONNECTION_HOST
              value: {{ .Values.database.host }}
            - name: DATABASE_CONNECTION_PORT
              value: {{ quote .Values.database.port }}
            - name: DATABASE_CONNECTION_DBNAME
              value: {{ .Values.database.dbname }}
            - name: DATABASE_CONNECTION_USER
              value: {{ .Values.database.user }}
            - name: DATABASE_CONNECTION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: slash10k
                  key: db-password
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: slash10k
                  key: admin-password
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slash10k
                  key: {{ .Values.discordTokenSecretName }}
            - name: APPLICATION_ID
              value: {{ .Values.applicationId | quote }}
            - name: VERSION
              value: {{ .Values.image.tag }}
      imagePullSecrets:
        - name: regcred
  strategy:
    type: Recreate
