#! /bin/bash

version=$(cat version)

major=$(echo $version | cut -d. -f1)
minor=$(echo $version | cut -d. -f2)
patch=$(echo $version | cut -d. -f3)

patch=$((patch + 1))
newVersion=$major.$minor.$patch

echo "$newVersion" > version
sed -i "s/$version/$newVersion/" deployment/values.yaml
sed -i "s/$version/$newVersion/" deployment/Chart.yaml
