CREATE TABLE IF NOT EXISTS debts (
    id SERIAL PRIMARY KEY,
    amount INTEGER NOT NULL,
    description TEXT NOT NULL,
    date DATE NOT NULL,
    user_id INTEGER REFERENCES players(id) ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS debts_mig_seq START WITH 1 INCREMENT BY 1;